# Generated by Django 2.2.3 on 2019-11-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADRDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('location', models.CharField(max_length=100)),
                ('medicine', models.CharField(max_length=100)),
                ('medicine_category', models.IntegerField()),
                ('label', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('disease', models.CharField(max_length=100)),
                ('medication', models.CharField(max_length=100)),
            ],
        ),
    ]
